name: Clean Spotify
on:
  workflow_dispatch:

env:
  SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
  SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
  REMOVE_AFTER: ${{ secrets.REMOVE_AFTER }} # Don't setup if you want to clean up your Spotify library completely

jobs:
  unlike_albums:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy==2.23.0
          
      - name: Unlike albums
        run: python -c 'from dags.scripts.spotify_unlike_albums import main;
                        main("${{ secrets.REFRESH_TOKEN }}")'


  unlike_tracks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy==2.23.0
      
      - name: Unlike tracks
        run: python -c 'from dags.scripts.spotify_unlike_tracks import main;
                        main("${{ secrets.REFRESH_TOKEN }}")'

  unfollow_playlists:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy==2.23.0
                        
      - name: Unfollow playlists
        run: python -c 'from dags.scripts.spotify_remove_playlists import main;
                        main("${{ secrets.REFRESH_TOKEN }}")'